# Generated by Django 5.2.9 on 2025-12-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterrecord',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='masterrecord',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='typedefinition',
            name='description',
        ),
        migrations.AlterField(
            model_name='masterrecord',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.typedefinition'),
        ),
        migrations.AlterField(
            model_name='typedefinition',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
