# Generated by Django 5.2.9 on 2025-12-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_masterrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrecord',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.typedefinition'),
        ),
    ]
