# Generated by Django 5.2.9 on 2025-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_masterrecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedefinition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
